[package]
name = "intermediate-theorem-format"
version = "0.1.0"
edition = "2021"

[dependencies]
move-model.workspace = true
log.workspace = true
num.workspace = true
ethnum.workspace = true
petgraph.workspace = true
indexmap.workspace = true
z3.workspace = true

[lib]
doctest = false
