[package]
name = "Prover"
edition = "2024.beta"

[dependencies]
MoveStdlib = { git = "https://github.com/asymptotic-code/sui.git", subdir = "crates/sui-framework/packages/move-stdlib", rev = "important_pures", override = true }

[addresses]
prover = "0x0"
